version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: myproject_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myproject
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: myproject_app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: 