basePath: /
definitions:
  healthcheck.HealthResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the NeedoBackend service
  title: NeedoBackend API
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Returns the health status of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.HealthResponse'
      summary: Health Check endpoint
      tags:
      - health
swagger: "2.0"
